name: Cypress Smoke Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress smoke + generate HTML report  
        run: npm run cy:run:smoke && npm run report:merge && npm run report:html

      - name: Upload Mochawesome HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-html-report
          path: cypress/reports/html

      - name: Upload Mochawesome JSON + merged JSON
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-json
          path: |
            cypress/reports/mochawesome
            cypress/reports/mochawesome-merged.json

      - name: Upload screenshots (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/reports/screenshots
          if-no-files-found: ignore

      - name: Upload videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/reports/videos
          if-no-files-found: ignore
